Convert BaseEntityType to interface
OData/odata.net pull request #1741
Opened 2020-04-09 19:59 UTC by weitzhandler

Fixes #1735

2020-04-20 20:11 UTC, chrisspre commented on src/Microsoft.OData.Client/BaseEntityType.cs
> +		protected internal DataServiceContext Context { get; set; }
Can't this be simplified to just `public DataServiceContext Context { get; set; }` instead of the explicit interface implementation?

2020-06-12 04:16 UTC, Sreejithpin commented
Hi,
 We recently had changed our project structure.  Can you please either rebase your code with out new master and update your PR, or create a new branch from master and make your updates in that branch and put a PR. Thanks a lot

2021-01-22 08:15 UTC, KenitoInc commented
@weitzhandler 
Hey,
Kindly rebase your PR and fix conflicts.

2021-03-07 03:01 UTC, weitzhandler commented
@KenitoInc sorry for the delay.
Rebase completed.

2021-04-08 01:21 UTC, weitzhandler commented
@Sreejithpin?

2021-05-05 12:35 UTC, KenitoInc requested changes

2021-05-05 12:35 UTC, KenitoInc commented on src/Microsoft.OData.Client/BaseEntityType.cs
> +    /// Base type of entity type to include <see cref="T:Microsoft.OData.Client.DataServiceContext" /> for function and action invocation
We shouldn't be adding the `T:`

2021-05-05 12:35 UTC, KenitoInc commented on src/Microsoft.OData.Client/IBaseEntityType.cs
> +    /// Base type of entity type to include <see cref="T:Microsoft.OData.Client.DataServiceContext" /> for function and action invocation
```suggestion
    /// Base type of entity type to include <see cref="Microsoft.OData.Client.DataServiceContext" /> for function and action invocation

```

2021-05-05 18:52 UTC, weitzhandler commented on src/Microsoft.OData.Client/BaseEntityType.cs
> +    /// Base type of entity type to include <see cref="T:Microsoft.OData.Client.DataServiceContext" /> for function and action invocation
Done.

2021-05-05 18:52 UTC, weitzhandler commented on src/Microsoft.OData.Client/IBaseEntityType.cs
> +    /// Base type of entity type to include <see cref="T:Microsoft.OData.Client.DataServiceContext" /> for function and action invocation
Done.

2021-05-12 11:50 UTC, gathogojr approved these changes
LGTM

2021-05-12 11:58 UTC, KenitoInc approved these changes
We next to cleanup this in the next breaking change release.

2021-05-12 13:01 UTC, habbes commented on src/Microsoft.OData.Client/BaseEntityType.cs
> +        }
Why make these explicitly implement the interface instead of just making the backing properties public?

2021-05-12 13:02 UTC, habbes approved these changes

2021-05-12 17:56 UTC, merged