HttpClientRequestMessage: Fix UnwrapAggregateException.
OData/odata.net pull request #2021
Opened 2021-03-05 20:12 UTC by tfaller

### Description

UnwrapAggregateException of HttpClientRequestMessage can currently either re-throw incomplete exception informations (by skipping an exception layer) or cause a NPE.

UnwrapAggregateException tries to unwrap an exception two layers deep. This is wrong. I got here a NPE because the exception that was wrapped in the AggregateException had no InnerException. This PR fixes this simple mistake.

### Additional work necessary
none

2021-03-15 12:34 UTC, gathogojr approved these changes

2021-03-15 12:43 UTC, marabooy approved these changes

2021-03-23 16:53 UTC, KenitoInc requested changes
I suggest you add a test to validate this fix.

2021-06-08 07:03 UTC, habbes commented
@tfaller hi, I'm following up to check whether you'd be able to add the tests requested by @KenitoInc, or whether you need any additional support.

2021-06-17 22:09 UTC, tfaller commented
Hello @KenitoInc and @habbes , I've added a test now. It would be nice if you could pull this soon, because I'm encountering this bug many times in production. Thanks.

2021-06-18 04:55 UTC, KenitoInc approved these changes

2021-07-14 08:15 UTC, KenitoInc commented
Thanks for this PR @tfaller

2021-07-14 08:15 UTC, merged