Fix/2005 translate path select item
OData/odata.net pull request #2022
Opened 2021-03-08 13:40 UTC by KenitoInc

### Issues

*This pull request fixes issue #2005 .*

### Description

*Briefly describe the changes of this pull request.*

### Checklist (Uncheck if it is not completed)

- [ ] *Test cases added*
- [ ] *Build and test with one-click build and test script passed*

### Additional work necessary

*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

2021-03-09 18:51 UTC, xuzhg commented
>             string selectClause = null;

Because there're some many += on the string, it's not good perf.

---
In reply to: [794299975](https://github.com/OData/odata.net/pull/2022#issuecomment-794299975) [](ancestors = 794299975)

---
Refers to: src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs:35 in 54fb8cb. [](commit_id = 54fb8cb0da32e90b723e212f98db1141a8048166, deletion_comment = False)

2021-03-09 18:55 UTC, xuzhg commented on test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/SelectExpandBuilderTests.cs
> +        public void SelectWithDollarThisInFilterClauseShouldWork()
>InFilter [](start = 40, length = 8)

....InNestedDollarFilter...

2021-03-09 18:56 UTC, xuzhg commented on test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/SelectExpandBuilderTests.cs
> +
all of these tests can merge using on [Theory] test case, what do you think?

2021-03-09 18:56 UTC, xuzhg requested changes
:clock1:

2021-03-10 20:38 UTC, mikepizzo commented
>             string selectClause = null;

Beware that stringbuilder also has overhead.

---
In reply to: [794300637](https://github.com/OData/odata.net/pull/2022#issuecomment-794300637) [](ancestors = 794300637,794299975)

---
Refers to: src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs:35 in 54fb8cb. [](commit_id = 54fb8cb0da32e90b723e212f98db1141a8048166, deletion_comment = False)

2021-03-10 20:49 UTC, mikepizzo commented
A few minor comments to add to Sam's comments, otherwise looks good.

2021-03-11 13:20 UTC, KenitoInc commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +            }
There are some differences. I would prefer to leave them as they are.
What do you think @mikepizzo ?

2021-03-11 13:20 UTC, KenitoInc commented on test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/SelectExpandBuilderTests.cs
> +            Uri queryUri = new Uri("People?$select=RelatedSSNs($orderby=$this)", UriKind.Relative);
I have added

2021-03-11 13:20 UTC, KenitoInc commented on test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/SelectExpandBuilderTests.cs
> +        public void SelectWithDollarThisInFilterClauseShouldWork()
#Resolved

2021-03-11 13:21 UTC, KenitoInc commented on test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriBuilder/SelectExpandBuilderTests.cs
> +            Uri queryUri = new Uri("People?$select=RelatedSSNs($orderby=$this)", UriKind.Relative);
#Resolved

2021-03-11 13:21 UTC, KenitoInc commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +
#Resolved

2021-03-11 13:22 UTC, KenitoInc commented
> > ```
> >         string selectClause = null;
> > ```
> 
> Beware that stringbuilder also has overhead.
> 
> In reply to: [794300637](https://github.com/OData/odata.net/pull/2022#issuecomment-794300637) [](ancestors = 794300637,794299975)
> 
> Refers to: src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs:35 in [54fb8cb](https://github.com/OData/odata.net/commit/54fb8cb0da32e90b723e212f98db1141a8048166). [](commit_id = [54fb8cb](https://github.com/OData/odata.net/commit/54fb8cb0da32e90b723e212f98db1141a8048166), deletion_comment = False)

I have left as is until am sure adding stringbuilder will have any performance improvements.

2021-03-18 21:30 UTC, xuzhg approved these changes
:shipit:

2021-03-23 09:08 UTC, habbes commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +                        expandClause = firstFlag ? expandClause : string.Concat("$expand", ExpressionConstants.SymbolEqual);
There's no constant for $expand?

2021-03-23 09:12 UTC, habbes commented
@KenitoInc could you add a description for the changes made in this PR, it would help to follow along.

2021-03-30 06:15 UTC, gathogojr commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +                if(selectItem.GetType() == typeof(PathSelectItem))
```suggestion
                if (selectItem.GetType() == typeof(PathSelectItem))
```

2021-03-30 06:21 UTC, gathogojr commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +                if (selectItem.GetType() == typeof(ExpandedNavigationSelectItem))
```suggestion
                else if (selectItem.GetType() == typeof(ExpandedNavigationSelectItem))
```
So this check is not done if first `if` block was executed...

2021-03-30 06:22 UTC, gathogojr commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +                if (selectItem.GetType() == typeof(ExpandedReferenceSelectItem))
```suggestion
                else if (selectItem.GetType() == typeof(ExpandedReferenceSelectItem))
```
So this comparison is not done if any of the above `if` blocks were executed...

2021-03-30 06:34 UTC, gathogojr commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +            if (item.OrderByOption != null)
@KenitoInc Would switching `if` with `else if` in this and subsequent blocks help reduce the number of comparisons done?

2021-03-30 06:34 UTC, gathogojr commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +            return string.IsNullOrEmpty(res) ? null : string.Concat(ExpressionConstants.SymbolOpenParen, res, ExpressionConstants.SymbolClosedParen);
@KenitoInc Should you return `null` or empty string like the method was doing before?

2021-04-06 13:46 UTC, gathogojr approved these changes
LGTM

2021-04-06 22:30 UTC, KenitoInc commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +                if (selectItem.GetType() == typeof(PathSelectItem))
`ExpandedNavigationSelectItem` inherits from `ExpandedReferenceSelectItem` so we need to have a clear distinction between the two, that's why we are using `GetType() == typeof`

2021-04-06 22:31 UTC, KenitoInc commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +                res += "$filter=" + nodeToStringBuilder.TranslateFilterClause(item.FilterOption);
This has been an open debate in this PR. 
cc @marabooy

2021-04-06 22:35 UTC, KenitoInc commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +                    }
It appears twice only. For now I don't think it's worth creating a new method because of that.

2021-04-06 22:36 UTC, KenitoInc commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +                else if (selectItem.GetType() == typeof(ExpandedNavigationSelectItem))
Explained this here https://github.com/OData/odata.net/pull/2022#discussion_r608221097

2021-04-06 22:59 UTC, KenitoInc commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +                if(selectItem.GetType() == typeof(PathSelectItem))
#Resolved

2021-04-06 23:01 UTC, KenitoInc commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +                    selectClause += this.Translate((PathSelectItem)selectItem);
#Resolved

2021-04-06 23:15 UTC, KenitoInc commented on src/Microsoft.OData.Core/Uri/SelectExpandClauseToStringBuilder.cs
> +                if (selectItem.GetType() == typeof(ExpandedNavigationSelectItem))
#Resolved

2021-04-08 06:59 UTC, habbes approved these changes

2021-04-08 07:03 UTC, merged