Add a * (STAR) in the OData context URL when expanding an entity
OData/odata.net pull request #2086
Opened 2021-05-12 07:41 UTC by cryogen

### Issues

*This pull request fixes issue https://github.com/OData/WebApi/issues/2088 and #2081*

### Description

*This change adds the STAR character (*) to the OData context URL when an entity is expanded and no selectors are specified. The way I (and apparently the team behind the Excel and PowerBI OData connector) read the OData spec suggests this character is required. As a result, it is not possible to use Excel or PowerBI to expand any data from an odata.net backed API. Test cases adjusted to match the change.*

### Checklist (Uncheck if it is not completed)

- [ ] *Test cases added*
- [ ] *Build and test with one-click build and test script passed*

2021-05-12 16:36 UTC, mikepizzo commented
We'll need to review this ramifications of this change carefully. I would love to fix Excel/PowerBI, but want to make sure we don't end up breaking other clients that are expecting the empty parens.

One option we could consider is the introduction of a MessageWriterSetting that a service can set to control whether or not the parens contains a star in the absence of expand options.

2021-06-04 09:08 UTC, cryogen commented
I understand the concern but at the end of the day this is the OData spec and it should be compliant. I've looked into adding the option but it's beyond my understanding of the code at this point in time

2021-09-10 04:05 UTC, mikepizzo requested changes
Thanks for the conribution!

The OData spec does not require the * and, unfortunately, adding it would break many existing applications that are not expecting the *.

We can look at adding it as an option, but beware that setting the option is likely to break existing clients.

2021-09-10 17:59 UTC, cryogen commented
I’ll close this in that case. Making the option is beyond my knowledge of the project and time commitment :)

thanks for the response

2021-09-10 17:59 UTC, closed without merging