Add vocabulary terms to Require Explicit Binding
OData/odata.net pull request #2614
Opened 2023-02-10 23:19 UTC by lisicase

### Issues

This pull request fixes #2611.

### Description

Adds two new vocabulary annotation terms: RequiresExplicitBinding and ExplicitOperationBindings.

### Checklist

- [x] Test cases added
- [x] Build and test with one-click build and test script passed

2023-02-11 17:47 UTC, mikepizzo commented on src/Microsoft.OData.Edm/Vocabularies/CoreVocabularies.xml
> +  <Term Name="ExplicitOperationBindings" Type="Collection(Core.QualifiedBoundOperationName)">
>Core.QualifiedBoundOperationName [](http://example.com/codeflow?start=58&length=32)

The definition of this term also needs to be added to the PR

2023-02-11 17:48 UTC, mikepizzo commented on src/Microsoft.OData.Edm/Vocabularies/CoreVocabularies.xml
> +  </Term>
Note that, in the final version of the OASIS PR, the Description was updated and a LongDescription was added.

2023-02-11 17:51 UTC, mikepizzo commented on test/FunctionalTests/Microsoft.OData.Edm.Tests/Vocabularies/CoreVocabularyTests.cs
> +            Assert.Equal("Collection(Org.OData.Core.V1.QualifiedBoundOperationName)", explicitOperationBindingsType.FullTypeName());
>QualifiedBoundOperationName [](http://example.com/codeflow?start=55&length=27)

Once you add the QualifiedBoundOperationName, you'll want to add a test to retrieve and validate that term and then verify that explicitOperationBindingsType is of that type.

2023-02-11 17:52 UTC, mikepizzo requested changes
:clock1:

2023-02-14 00:24 UTC, mikepizzo approved these changes
:shipit:

2023-02-14 02:52 UTC, xuzhg approved these changes

2023-02-14 16:48 UTC, merged