fix ArgumentNullException exception when loading invalid CSDL
OData/odata.net pull request #2918
Opened 2024-04-03 13:07 UTC by quanterion

When loading invalid CSDL model via
**CsdlReader.Parse** we get correct exception **EdmException**. But if we do it via **CsdlReader.TryParse** with **ignoreUnexpectedAttributesAndElements** option enabled we get instead **System.ArgumentNullException: Value cannot be null. (Parameter 'key'**) because adding null version fails here https://github.com/OData/odata.net/blob/main/src/Microsoft.OData.Edm/Csdl/CsdlReader.cs#L339 and as get no critical errors due to https://github.com/OData/odata.net/blob/main/src/Microsoft.OData.Edm/Csdl/CsdlReader.cs#L483

2024-04-11 07:59 UTC, gathogojr commented
Hi @quanterion. Thank you for your pull request contribution. Could you please add a test to confirm the behaviour resulting from your change?

2024-04-12 07:50 UTC, wachugamaina commented on src/Microsoft.OData.Edm/Csdl/CsdlReader.cs
> +            if (!this.HasIntolerableError() && parsed)
Do we have tests covering both parsed is true and false ?

2024-06-06 12:21 UTC, ElizabethOkerio commented
@quanterion Add tests

2024-06-06 12:22 UTC, ElizabethOkerio requested changes
Add tests

2024-12-05 06:59 UTC, WanjohiSammy commented
@quanterion as there has been no activity or response on this PR for a while, I am going to close it for now. If you would like to continue working on it, please feel free to reopen it.

2024-12-05 06:59 UTC, closed without merging